import type { Metadata } from "next";
import { Geist, Geist_Mono, Funnel_Display } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// const funnelDisplay = Funnel_Display({
//   variable: "--font-funnel-display",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/neue-haas-grotesk-display-pro"
          rel="stylesheet"
        />
      </head>
      <body
        style={{ overflow: "hidden" }}
        className={`[font-family:'Neue_Haas_Grotesk_Display_Pro']   antialiased`}
      >
        <div className="min-h-[100dvh] ">
          <main className=" main relative">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
